version: "3.9"

services:
  app:
    build: .
    container_name: snippetbox-app
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_DSN: "root:secret@tcp(db:3306)/snippetbox?parseTime=true"
    networks:
      - snippetbox-net

  db:
    image: mysql:8
    container_name: snippetbox-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: snippetbox
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - snippetbox-net

networks:
  snippetbox-net:

volumes:
  mysql-data:
